# Determinan

## Determinan 
Determinan[1] adalah nilai yang dapat dihitung dari elemen-elemen suatu matriks yang memiliki jumlah baris dan kolom yang sama. Dengan kata lain, matriks persegi adalah matriks yang memiliki dimensi yang sama baik untuk baris maupun kolomnya $(A_n X_n)$, sehingga jika digambarkan, bentuk matriksnya menyerupai sebuah persegi  
contoh matriks determinan 2x2:  
$
\begin{matrix}
A = \begin{bmatrix}
    2 & 3 \\
    1 & 2 
  \end{bmatrix}
\end{matrix}
$

## Sifat-sifat determinan

1. Nilai determinan dari matriks identitas adalah satu.

In [8]:
import numpy as np
A = np.array([[2,4],[3,2]])
B = np.array([[3,1,3],[2,3,2],[5,3,2]])
C = np.array([[1,0],[0,1]])
D = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(f'determinan dari matriks D1 : {(round(np.linalg.det(D)))}')


determinan dari matriks D1 : 1


2. Determinan dari hasil perkalian matriks A dan B sama dengan perkalian determinan matriks A dengan determinan matriks B.  
$det(AB) = det(A) * det(B)$  
$jika A = A^1 maka det(I) = det(A) * det(A^1)$

In [10]:
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
detA = np.linalg.det(A)
detB = np.linalg.det(B)
det_A_inv = np.linalg.det(A)
det_B_inv = np.linalg.det(B)
print(f' det(A) * det(B) = {round(np.dot(detA,det_A_inv))}')


 det(A) * det(B) = 64


3. Menukar kolom atau baris akan mengakibatkan perubahan tanda pada nilai determinan.

In [11]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [12]:
import numpy as np
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
print(A)
AA = np.linalg.det(A)
print(round(AA))
A1 = RowSwap(A, 0 , 1)
print(A1)
detA1 = np.linalg.det(A1)
print(round(detA1))

[[1 4 2]
 [1 1 1]
 [3 2 1]]
5
[[1. 1. 1.]
 [1. 4. 2.]
 [3. 2. 1.]]
-5


4. Apabila nilai-nilai dalam suatu baris atau kolom pada matriks merupakan kelipatan dari nilai-nilai dalam baris atau kolom lainnya, maka determinannya akan menjadi nol.

In [15]:
A = np.array([[1,4,2],[2,8,4],[3,2,1]])
print(A)
print(round(np.linalg.det(A)))

[[1 4 2]
 [2 8 4]
 [3 2 1]]
0


5. jika K adalah skalar maka 
$$det(KA) = K^2 * det(A) $$

In [17]:
K = 2
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
K_A = np.dot(K,A)
detA = np.linalg.det(A)
detK_A = np.linalg.det(K_A)
detK_AM = np.dot(2**3,round(detA))
print(detK_A)
print(detK_AM)

40.0
40


6. apabila melakukan operasi baris elementer ke matriksnya maka tidak akan mengubah determinan dan inversenya

In [16]:
import numpy as np
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
print(A)
AA = np.linalg.det(A)
print(round(AA))
A1 = RowSwap(A, 0 , 1)
print(A1)
detA1 = np.linalg.det(A1)
print(round(detA1))

[[1 4 2]
 [1 1 1]
 [3 2 1]]
5
[[1. 1. 1.]
 [1. 4. 2.]
 [3. 2. 1.]]
-5


7. Determinan dari matriks A setelah dilakukan transpose sama dengan determinan matriks A sebelumnya.

In [18]:
import numpy as np
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
AT = A.transpose()
detAT = np.linalg.det(AT)
detA = np.linalg.det(A)
print(round(detAT))
print(round(detA))


5
5


## Matriks segitiga atas, bawah 

In [19]:
import numpy as np
A = np.array([[1,4,2],[0,4,1],[0,0,1]])
B = np.array([[1,0,0],[1,4,0],[1,4,2]])
print(f'segitiga atas \n{A}')
print(f'segitiga bawah \n{B}')
detA = np.linalg.det(A)
detB = np.linalg.det(B)
detAM = A[0][0] * A[1][1] * A[2][2]
detBM = B[0][0] * B[1][1] * B[2][2]
print(detA)
print(detAM)
print(round(detB))
print(detBM)

segitiga atas 
[[1 4 2]
 [0 4 1]
 [0 0 1]]
segitiga bawah 
[[1 0 0]
 [1 4 0]
 [1 4 2]]
4.0
4
8
8


## Determinan dengan ekpansi kofaktor 

**Determinan ekpansi kofaktor[2]** adalah Metode dalam menghitung determinan matriks adalah suatu pendekatan yang fokus pada kemampuan perhitungan manual dan teoritis dengan menggunakan kofaktor.  
### Kelebihan Metode Ekspansi Kofaktor :  
1. Metode ini bisa digunakan untuk matriks yang memiliki ukuran persegi minimal 2x2.
2. Cocok bagi yang menyukai perhitungan manual dan pendekatan teoritis.
3. Penerapan konsep kofaktor juga berguna dalam menemukan invers dari sebuah matriks.


## Link Referensi :
[1] https://www.ruangguru.com/blog/cara-mencari-determinan-dan-invers-matriks   
[2] https://www.profematika.com/kelebihan-dan-kekurangan-metode-ekspansi-kofaktor/
