# Sistem Persamaan Linier

## Sistem Persaman Linier Dan Penyelesaian

sistem persaman linier adalah 

## Penjumlahan Mtriks 
Penjumlahan matriks adalaha .... misalkan matrikks dibawah ini yaitu matriks A dan matriks B sebagai berikut :
\begin{align*}
A=
\begin{bmatrix}
2&-3&4\\
1&0&-7
\end{bmatrix}
&&
B=
\begin{bmatrix}
6&2&-4\\
3&5&2
\end{bmatrix}
\end{align*}

### Penyelesaian Tunggal

Persamaan:

$x_1+3x_2=5$
  
$x_1-2x_2=-5$
  
Solusi:

$x_1=-1,x_2=2$

### Sistem tidak ada penyelesain

$x_1+3x2=5$

$x_1+3x_2=0$

### Sistem dengan tak terhingga penyelesaian

$x_1+3x_2=5$

$2x_1+6x_2=10$

## Penyelesaian sistem persamaan linier (Eliminasi gauss)


### Eliminasi Gauss

  * Serangkaian langkah yang disebut *operasi baris* yang mempertahankan penyelesaian sistem 

    a. Tukarkan posisi kedua persamaan 
    
    b. Kalikan persamaaan dengan bilangan apapun yang bukan nol 
    
    c. Gantikan suatu persamaan dengan jumlah persamaan itu sendiri dan kelipatan persmaan lainnya  

 $x_1-x_2+x_3=3$ 

 $2x_1+x_2+8x_3=18$

 $4x_1+2x_2-3x_3=-2$ 

menjadi :

$x_1-x_2+x_3=3$

$x_2+2x_3=4$

$x_3=2$

In [1]:
import numpy as np

A = np.array([[8,9,1,19],[1,2,3,9],[2,1,1,5]])

print(A)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


In [2]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [3]:
A1 = RowSwap(A, 0, 1)
print(A1, '\n')

A2 = RowAdd(A1, 0, 1, -8)
print(A2, '\n')

A3 = RowAdd(A2, 0, 2, -2)
print(A3, '\n')

A4 = RowScale(A3, 1, -1/7)
print(A4, '\n')

A5 = RowAdd(A4, 1, 2, 3)
print(A5, '\n')


A6 = RowScale(A5, 2, 1/4.85714286)
print(A6)

[[ 1.  2.  3.  9.]
 [ 8.  9.  1. 19.]
 [ 2.  1.  1.  5.]] 

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  2.   1.   1.   5.]] 

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  0.  -3.  -5. -13.]] 

[[  1.           2.           3.           9.        ]
 [ -0.           1.           3.28571429   7.57142857]
 [  0.          -3.          -5.         -13.        ]] 

[[ 1.          2.          3.          9.        ]
 [-0.          1.          3.28571429  7.57142857]
 [ 0.          0.          4.85714286  9.71428571]] 

[[ 1.          2.          3.          9.        ]
 [-0.          1.          3.28571429  7.57142857]
 [ 0.          0.          1.          2.        ]]


In [4]:
x3 = 2
print('x3 = ', x3)
x2 = round(- 3.28571429 * 2 +  7.57142857)
print('x2 = ', x2)
x1 = round(9 - (2 * x2) - (3 * 2))
print('x1 = ', x1)

x3 =  2
x2 =  1
x1 =  1
