# Hitung EigenValue & EigenVector menggunakan numpy matriks 3x3

### buat matrik terlebih dahulu dengan ordo 3x3 :
$$ 
C = \begin{pmatrix}
4 & 1 & 0 \\
0 & 2 & 0 \\
0 & 0 & 0 
\end{pmatrix}
$$

### Menemukan Nilai Eigen (Eigenvalues)
Nilai eigen ($\lambda$) ditemukan dengan menyelesaikan persamaan karakteristik:
$$ 
\det(C - \lambda I) = 0 
$$
Di mana $ I $ adalah matriks identitas 3x3.

1. Matriks $ C - \lambda I $ adalah:
$$ 
C - \lambda I = \begin{pmatrix}
4 - \lambda & 1 & 0 \\
0 & 2 - \lambda & 0 \\
0 & 0 & 0 - \lambda 
\end{pmatrix}
= \begin{pmatrix}
4 - \lambda & 1 & 0 \\
0 & 2 - \lambda & 0 \\
0 & 0 & -\lambda 
\end{pmatrix}
$$

2. Determinan dari $ C - \lambda I $ adalah:
$$ 
\det(C - \lambda I) = \det \begin{pmatrix}
4 - \lambda & 1 & 0 \\
0 & 2 - \lambda & 0 \\
0 & 0 & -\lambda 
\end{pmatrix}
= (4 - \lambda)(2 - \lambda)(-\lambda) 
$$

3. Persamaan karakteristik adalah:
$$ 
(4 - \lambda)(2 - \lambda)(-\lambda) = 0 
$$

4. Menyelesaikan persamaan ini, kita mendapatkan nilai eigen:
$$ 
\lambda_1 = 4, \quad \lambda_2 = 2, \quad \lambda_3 = 0 
$$

### Menemukan Vektor Eigen (Eigenvectors)
Untuk setiap nilai eigen $\lambda$, kita temukan vektor eigen $\mathbf{v}$ yang memenuhi:
$$ 
(C - \lambda I)\mathbf{v} = 0 
$$

1. Untuk $\lambda_1 = 4$:
$$ 
(C - 4I) = \begin{pmatrix}
0 & 1 & 0 \\
0 & -2 & 0 \\
0 & 0 & -4 
\end{pmatrix}
$$
Kita harus menyelesaikan:
$$ 
\begin{pmatrix}
0 & 1 & 0 \\
0 & -2 & 0 \\
0 & 0 & -4 
\end{pmatrix}
\begin{pmatrix}
v_{11} \\
v_{12} \\
v_{13} 
\end{pmatrix}
= 
\begin{pmatrix}
0 \\
0 \\
0 
\end{pmatrix}
$$
Ini menghasilkan:
$$ 
v_{11} \text{ bebas}, \quad v_{12} = 0, \quad v_{13} = 0 
$$
Vektor eigen yang sesuai adalah:
$$ 
\mathbf{v}_1 = \begin{pmatrix}
1 \\
0 \\
0 
\end{pmatrix}
$$

2. Untuk $\lambda_2 = 2$:
$$ 
(C - 2I) = \begin{pmatrix}
2 & 1 & 0 \\
0 & 0 & 0 \\
0 & 0 & -2 
\end{pmatrix}
$$
Kita harus menyelesaikan:
$$ 
\begin{pmatrix}
2 & 1 & 0 \\
0 & 0 & 0 \\
0 & 0 & -2 
\end{pmatrix}
\begin{pmatrix}
v_{21} \\
v_{22} \\
v_{23} 
\end{pmatrix}
= 
\begin{pmatrix}
0 \\
0 \\
0 
\end{pmatrix}
$$
Ini menghasilkan:
$$ 
2v_{21} + v_{22} = 0, \quad v_{23} = 0 \implies v_{22} = -2v_{21}
$$
Vektor eigen yang sesuai adalah:
$$ 
\mathbf{v}_2 = \begin{pmatrix}
1 \\
-2 \\
0 
\end{pmatrix}
$$

3. Untuk $\lambda_3 = 0$:
$$ 
(C - 0I) = \begin{pmatrix}
4 & 1 & 0 \\
0 & 2 & 0 \\
0 & 0 & 0 
\end{pmatrix}
$$
Kita harus menyelesaikan:
$$ 
\begin{pmatrix}
4 & 1 & 0 \\
0 & 2 & 0 \\
0 & 0 & 0 
\end{pmatrix}
\begin{pmatrix}
v_{31} \\
v_{32} \\
v_{33} 
\end{pmatrix}
= 
\begin{pmatrix}
0 \\
0 \\
0 
\end{pmatrix}
$$
Ini menghasilkan:
$$ 
4v_{31} + v_{32} = 0, \quad 2v_{32} = 0 \implies v_{31} = 0, \quad v_{32} = 0, \quad v_{33} \text{ bebas}
$$
Vektor eigen yang sesuai adalah:
$$ 
\mathbf{v}_3 = \begin{pmatrix}
0 \\
0 \\
1 
\end{pmatrix}
$$

### Kesimpulan
Nilai eigen dan vektor eigen dari matriks $ C $ adalah:
- **Nilai Eigen**:
  $$
  \lambda_1 = 4, \quad \lambda_2 = 2, \quad \lambda_3 = 0 
  $$

- **Vektor Eigen**:
  $$
  \mathbf{v}_1 = \begin{pmatrix}
  1 \\
  0 \\
  0 
  \end{pmatrix}, \quad 
  \mathbf{v}_2 = \begin{pmatrix}
  1 \\
  -2 \\
  0 
  \end{pmatrix}, \quad 
  \mathbf{v}_3 = \begin{pmatrix}
  0 \\
  0 \\
  1 
  \end{pmatrix}
  $$



In [1]:
import numpy as np

# Definisikan matriks 3x3 yang memiliki nilai eigen 4, 2, 0
C_3x3 = np.array([[4, 1, 0],
                  [0, 2, 0],
                  [0, 0, 0]])

# Hitung nilai eigen dan vektor eigen
eigenvalues_C_3x3, eigenvectors_C_3x3 = np.linalg.eig(C_3x3)

print("\nMatriks 3x3 C:")
print(C_3x3)

print("\nNilai Eigen untuk matriks 3x3:")
print(eigenvalues_C_3x3)

print("\nVektor Eigen untuk matriks 3x3:")
print(eigenvectors_C_3x3)



Matriks 3x3 C:
[[4 1 0]
 [0 2 0]
 [0 0 0]]

Nilai Eigen untuk matriks 3x3:
[4. 2. 0.]

Vektor Eigen untuk matriks 3x3:
[[ 1.         -0.4472136   0.        ]
 [ 0.          0.89442719  0.        ]
 [ 0.          0.          1.        ]]
