# Membuat persaman dengan varibel

## Membuat 4 persaman dengan 4 varibel dan mencari solusinya pakai invers matriks dengan eliminasi gauss jordan

* Pertama kita akan buat fungsi yang diperlukan dulu seperti berikut :  
Sebelum itu kita **definisikan fungsi python** yang diperlukan diantaranya :  
1. **RowSwap** adalah fungsi digunakan untuk menukar posisi dua baris dalam sebuah matriks.  
2. **RowScale** adalah fungsi digunakan untuk mengalikan setiap elemen dalam sebuah baris matriks dengan skalar.  
3. **RowAdd** adalah fungsi digunakan untuk menambahkan satu baris matriks dengan baris lainnya, dengan setiap elemen baris pertama ditambahkan dengan elemen yang sesuai dari baris kedua.  

In [1]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

* Langkah selanjutnya tentu kita akan buat persamaanya dulu bebas

In [2]:
# Import library numpy dan memasukkan persamaan dalam bentuk matrix
import numpy as np
A = np.array([[5,2,10,16],[3,1,0,-2],[3,1,-9,-19],[4,1,0,-3]])
print(f"Matrix A  = \n{A}")
print("\n")

Matrix A  = 
[[  5   2  10  16]
 [  3   1   0  -2]
 [  3   1  -9 -19]
 [  4   1   0  -3]]




* Langkah selanjutnya akan gabungkan persamaan tersebut dengan matrik invers

In [3]:
# Import library numpy dan memasukkan persamaan dalam bentuk matrix
import numpy as np
A = np.array([[5,2,10,16,1,0,0,0],[3,1,0,-2,0,1,0,0],[3,1,-9,-19,0,0,1,0],[4,1,0,-3,0,0,0,1]])
print(f"Matrix A  = \n{A}")
print("\n")

Matrix A  = 
[[  5   2  10  16   1   0   0   0]
 [  3   1   0  -2   0   1   0   0]
 [  3   1  -9 -19   0   0   1   0]
 [  4   1   0  -3   0   0   0   1]]




* langkah selanjutnya akan melakukan serangkaian operasi baris pada matriks tersebut dengan tujuan untuk memperoleh matriks eselon atau PE yaitu (5) agar nialai itu (1) disini akan melakukan operasi pengurangan pada (b1-b4), seperti berikut :

In [4]:
A1= RowAdd(A,3,0,-1)
print(A1)

[[  1.   1.  10.  19.   1.   0.   0.  -1.]
 [  3.   1.   0.  -2.   0.   1.   0.   0.]
 [  3.   1.  -9. -19.   0.   0.   1.   0.]
 [  4.   1.   0.  -3.   0.   0.   0.   1.]]


* selanjutnya akan melakukan serangkaian operasi baris pada matriks tersebut dengan tujuan untuk memperoleh setiap elemen dibawah matriks eselon atau PE(5) agar nilainya itu (0) disini akan melakukan beberapa operasi pengurangan pada (b2-3b1),(b3-3b1),(b4-4b1) seperti berikut :

In [5]:
A2= RowAdd(A1,0,1,-3)
print(A2)

[[  1.   1.  10.  19.   1.   0.   0.  -1.]
 [  0.  -2. -30. -59.  -3.   1.   0.   3.]
 [  3.   1.  -9. -19.   0.   0.   1.   0.]
 [  4.   1.   0.  -3.   0.   0.   0.   1.]]


In [6]:
A3= RowAdd(A2,0,2,-3)
print(A3)

[[  1.   1.  10.  19.   1.   0.   0.  -1.]
 [  0.  -2. -30. -59.  -3.   1.   0.   3.]
 [  0.  -2. -39. -76.  -3.   0.   1.   3.]
 [  4.   1.   0.  -3.   0.   0.   0.   1.]]


In [7]:
A4= RowAdd(A3,0,3,-4)
print(A4)

[[  1.   1.  10.  19.   1.   0.   0.  -1.]
 [  0.  -2. -30. -59.  -3.   1.   0.   3.]
 [  0.  -2. -39. -76.  -3.   0.   1.   3.]
 [  0.  -3. -40. -79.  -4.   0.   0.   5.]]


* selanjutnya akan melakukan serangkaian operasi baris pada matriks tersebut dengan tujuan untuk memperoleh matriks eselon atau PE selanjutnya yaitu(-2) agar nilainya itu (1) disini akan melakukan operasi pada (b2-b4) seperti berikut :

In [8]:
A5= RowAdd(A4,3,1,-1)
print(A5)

[[  1.   1.  10.  19.   1.   0.   0.  -1.]
 [  0.   1.  10.  20.   1.   1.   0.  -2.]
 [  0.  -2. -39. -76.  -3.   0.   1.   3.]
 [  0.  -3. -40. -79.  -4.   0.   0.   5.]]


* selanjutnya akan melakukan serangkaian operasi baris pada matriks tersebut dengan tujuan untuk memperoleh setiap elemen dibawah atau diatasnya matriks eselon atau PE yaitu (-2) agar nilainya itu (0) disini akan melakukan beberapa operasi pada (b1-b2),(b3+2b2),(b4+3b2) seperti berikut :

In [9]:
A6= RowAdd(A5,1,0,-1)
print(A6)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.  10.  20.   1.   1.   0.  -2.]
 [  0.  -2. -39. -76.  -3.   0.   1.   3.]
 [  0.  -3. -40. -79.  -4.   0.   0.   5.]]


In [10]:
A7= RowAdd(A6,1,2,2)
print(A7)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.  10.  20.   1.   1.   0.  -2.]
 [  0.   0. -19. -36.  -1.   2.   1.  -1.]
 [  0.  -3. -40. -79.  -4.   0.   0.   5.]]


In [11]:
A8= RowAdd(A7,1,3,3)
print(A8)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.  10.  20.   1.   1.   0.  -2.]
 [  0.   0. -19. -36.  -1.   2.   1.  -1.]
 [  0.   0. -10. -19.  -1.   3.   0.  -1.]]


* selanjutnya akan melakukan operasi baris pada matriks tersebut dengan tujuan untuk memperoleh matriks eselon atau PE selanjutnya yaitu(-19) agar nilainya itu (1) disini akan melakukan beberapa operasi pada (b2+b4) agar diatas PE(-19) itu nilainya(0) seperti berikut :

In [12]:
A9= RowAdd(A8,3,1,1)
print(A9)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.   0.   1.   0.   4.   0.  -3.]
 [  0.   0. -19. -36.  -1.   2.   1.  -1.]
 [  0.   0. -10. -19.  -1.   3.   0.  -1.]]


* selanjutnya akan melakukan serangkaian operasi baris pada matriks tersebut dengan tujuan untuk memperoleh matriks eselon atau PE selanjutnya yaitu(-19) agar nilainya itu (1) disini akan melakukan operasi pada (b4*2) agar supaya mudah untuk mendapatkan angka 1 seperti berikut :

In [13]:
A10= RowScale(A9,3,2)
print(A10)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.   0.   1.   0.   4.   0.  -3.]
 [  0.   0. -19. -36.  -1.   2.   1.  -1.]
 [  0.   0. -20. -38.  -2.   6.   0.  -2.]]


* selanjut untuk merubah PE(-19) agar menjadi (1) itu tinggal melakukkan operasi pengurangan (b3-b4) seperti berikut :

In [14]:
A11= RowAdd(A10,3,2,-1)
print(A11)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.   0.   1.   0.   4.   0.  -3.]
 [  0.   0.   1.   2.   1.  -4.   1.   1.]
 [  0.   0. -20. -38.  -2.   6.   0.  -2.]]


* selanjutnya disini akan melakukan operasi baris pada matriks tersebut dengan tujuan untuk memperoleh elemen dibawah matriks eselon atau PE(-19) tadi agar nilainya itu (0) disini akan melakukan operasin pada (b4+20b3) seperti berikut :

In [15]:
A12= RowAdd(A11,2,3,20)
print(A12)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.   0.   1.   0.   4.   0.  -3.]
 [  0.   0.   1.   2.   1.  -4.   1.   1.]
 [  0.   0.   0.   2.  18. -74.  20.  18.]]


* selanjutnya akan melakukan operasi baris pada matriks tersebut dengan tujuan untuk memperoleh matriks eselon atau PE selanjutnya yaitu(2) agar nilainya itu (1) disini akan melakukan operasi pada (b4/2) agar supaya mudah untuk mendapatkan angka 1 seperti berikut :

In [16]:
A13= RowScale(A12,3,1/2)
print(A13)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.   0.   1.   0.   4.   0.  -3.]
 [  0.   0.   1.   2.   1.  -4.   1.   1.]
 [  0.   0.   0.   1.   9. -37.  10.   9.]]


* selanjutnya disini akan melakukan operasi baris pada matriks tersebut dengan tujuan untuk memperoleh elemen diatas matriks eselon atau PE(2) tadi agar nilainya itu (0) disini akan melakukan beberapa operasi pada (b3-2b4),(b2-b4),(b1+b4) seperti berikut :

In [17]:
A14= RowAdd(A13,3,0,1)
print(A14)

[[  1.   0.   0.   0.   9. -38.  10.  10.]
 [  0.   1.   0.   1.   0.   4.   0.  -3.]
 [  0.   0.   1.   2.   1.  -4.   1.   1.]
 [  0.   0.   0.   1.   9. -37.  10.   9.]]


In [18]:
A15= RowAdd(A14,3,1,-1)
print(A15)

[[  1.   0.   0.   0.   9. -38.  10.  10.]
 [  0.   1.   0.   0.  -9.  41. -10. -12.]
 [  0.   0.   1.   2.   1.  -4.   1.   1.]
 [  0.   0.   0.   1.   9. -37.  10.   9.]]


In [19]:
A16= RowAdd(A15,3,2,-2)
print(A16)

[[  1.   0.   0.   0.   9. -38.  10.  10.]
 [  0.   1.   0.   0.  -9.  41. -10. -12.]
 [  0.   0.   1.   0. -17.  70. -19. -17.]
 [  0.   0.   0.   1.   9. -37.  10.   9.]]


disini sudah mendapatkan invers dari $A^1$,selanjutnya disini bisa lakukaan opersi perkalian yaitu $A^1$ dengan B unutuk mendapatkan matriks yang benilai solusi dari persamaan tersebut
 
$$
\begin{matrix}
X = A^1 B = \begin{bmatrix}
    9 & -38 & 10 & 10 \\
    -9 & 41 & -10 & -12 \\
    -17 & 70 & -19 & -17 \\
    9 & -37 & 10 & 9 
  \end{bmatrix}
\quad
\begin{bmatrix}
    16 \\
    4 \\
    -4 \\
    5
  \end{bmatrix}
\end{matrix}
$$

dan hasilnya sebagai berikut :

In [20]:
A_inverse = np.array([[9, -38, 10, 10], [-9, 41, -10, -12],[-17, 70, -19, -17], [9,-37,10,9]])
b = np.array([[16], [4], [-4], [5]])

x = A_inverse @ b

print(x)

[[ 2]
 [ 0]
 [-1]
 [ 1]]
