# Determinan Matriks 4x4 dengan Ekpansi Kofaktor 

**1. langkah pertama buat matriksnya terlebih dahulu dengan ordo 4x4**

   
$\begin{matrix}
A = \begin{bmatrix}
    2 & 3 & 4 & 5\\
    1 & 1 & 1 & 1\\
    3 & 2 & 2 & 2\\
    3 & 2 & 5 & 4
  \end{bmatrix}
\end{matrix}
$

**2. selanjutnya tulis rumus determinan disini, mengambil baris ke-2**


$ det(A) = a_{21} c_{21} + a_{22} c_{22}  + a_{23} c_{23} + a_{24} c_{24} $  

**3. selanjutnya tentukan kofaktor nya disini dari matriks A**


$c_{21} = (-1)^{2+1} det(M_{21})$  
$c_{22} = (-1)^{2+2} det(M_{22})$  
$c_{23} = (-1)^{2+3} det(M_{23})$  
$c_{24} = (-1)^{2+4} det(M_{24})$

**4. setelah itu kita akan cari satu-persatu determinan minor tersebut dari matriks A**

**5. **pertama : $M_{21}$****


$\begin{matrix}
  det(M21) = \begin{bmatrix}
    3 & 4 & 5 \\
    2 & 2 & 2 \\
    2 & 5 & 4
  \end{bmatrix}
\end{matrix}
$  


selanjutnya tulis rumus determinan, dan mengambil baris ke-2  
$det(M21) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$   


selanjutnya tentukan kofaktor dari matriks yang $M_{21}, M_{22}, M_{23}$  
* $c_{21} = (-1)^{2 + 1} det(KM21)$   

$
\begin{matrix}
  det(KM21) = \begin{bmatrix}
    4 & 5 \\
    5 & 4
  \end{bmatrix}
\end{matrix}
$  
$det(KM21) = 4.4 - 5.5 = 16 - 25 = -9$  


hasil 
$c_{21} = -1*-9$  


* $c_{22} = (-1)^{2+2}det(KM22)$   

$
\begin{matrix}
  det(KM22) = \begin{bmatrix}
    3 & 5 \\
    2 & 4
  \end{bmatrix}
\end{matrix}
$  
$det(KM22) = 3.4 - 2.5 = 12 - 10 = 2$  


hasil
$c_{22} = -1*2$  


* $c_{23} = (-1)^{2+3}det(KM23)$  
 
$
\begin{matrix}
  det(KM23) = \begin{bmatrix}
    3 & 4 \\
    2 & 5
  \end{bmatrix}
\end{matrix}
$  
$det(KM23) = 3.5 - 2.4 = 15 - 8 = 7$  


hasil
$c_{23} = -1*7$  


**hasil akhir dari $M_{21}$**  
$det(M21) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$  
$det(M21) = 2.(-1).(-9) + 2.1.2 + 2.(-1).7$  
$det(M21) = 18 + 4 - 14 = 8$  


dibuktikan dengan menggunakan numpy python 

In [2]:
import numpy as np
M21 = np.array([[3,4,5], [2,2,2], [2,5,4]])
detM21 = np.linalg.det(M21)
print(round(detM21))

8


**6. **kedua : $M_{22}$****


$\begin{matrix}
  det(M22) = \begin{bmatrix}
    2 & 4 & 5 \\
    3 & 2 & 2 \\
    3 & 5 & 4
  \end{bmatrix}
\end{matrix}
$  


selanjutnya tulis rumus determinan, dan mengambil baris ke-2  
$det(M21) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$   


selanjutnya tentukan kofaktor dari matriks yang $M_{21}, M_{22}, M_{23}$  
* $c_{21} = (-1)^{2 + 1} det(KM21)$   

$
\begin{matrix}
  det(KM21) = \begin{bmatrix}
    4 & 5 \\
    5 & 4
  \end{bmatrix}
\end{matrix}
$  
$det(KM21) = 4.4 - 5.5 = 16 - 25 = -9$  


hasil 
$c_{21} = -1*-9$  


* $c_{22} = (-1)^{2+2}det(KM22)$   

$
\begin{matrix}
  det(KM22) = \begin{bmatrix}
    2 & 5 \\
    3 & 4
  \end{bmatrix}
\end{matrix}
$  
$det(KM22) = 2.4 - 3.5 = 8 - 15 = -7$  


hasil
$c_{22} = -1*-7$  


* $c_{23} = (-1)^{2+3}det(KM23)$  
 
$
\begin{matrix}
  det(KM23) = \begin{bmatrix}
    2 & 4 \\
    3 & 5
  \end{bmatrix}
\end{matrix}
$  
$det(KM23) = 2.5 - 3.4 = 10 - 12 = -2$  


hasil
$c_{23} = -1*-2$  


**hasil akhir dari $M_{22}$**  
$det(M22) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$  
$det(M22) = 3.(-1).(-9) + 2.1.(-7) + 2.(-1).(-2)$  
$det(M22) = 27 - 14 + 4 = 17$  


dibuktikan dengan menggunakan numpy python 

In [4]:
import numpy as np
M22 = np.array([[2,4,5], [3,2,2], [3,5,4]])
detM22 = np.linalg.det(M22)
print(round(detM22))

17


**7. **ketiga : $M_{23}$****


$\begin{matrix}
  det(M23) = \begin{bmatrix}
    3 & 2 & 5 \\
    3 & 2 & 2 \\
    3 & 2 & 4
  \end{bmatrix}
\end{matrix}
$  


selanjutnya tulis rumus determinan, dan mengambil baris ke-2  
$det(M21) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$   


selanjutnya tentukan kofaktor dari matriks yang $M_{21}, M_{22}, M_{23}$  
* $c_{21} = (-1)^{2 + 1} det(KM21)$   

$
\begin{matrix}
  det(KM21) = \begin{bmatrix}
    2 & 5 \\
    2 & 4
  \end{bmatrix}
\end{matrix}
$  
$det(KM21) = 2.4 - 2.5 = 8 - 10 = -2$  


hasil 
$c_{21} = -1*-2$  


* $c_{22} = (-1)^{2+2}det(KM22)$   

$
\begin{matrix}
  det(KM22) = \begin{bmatrix}
    3 & 5 \\
    3 & 4
  \end{bmatrix}
\end{matrix}
$  
$det(KM22) = 3.4 - 3.5 = 12 - 15 = -3$  


hasil
$c_{22} = -1*-3$  


* $c_{23} = (-1)^{2+3}det(KM23)$  
 
$
\begin{matrix}
  det(KM23) = \begin{bmatrix}
    3 & 2 \\
    3 & 2
  \end{bmatrix}
\end{matrix}
$  
$det(KM23) = 3.2 - 3.2 = 6 - 6 = 0$  


hasil
$c_{23} = -1*-0$  


**hasil akhir dari $M_{23}$**  
$det(M23) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$  
$det(M23) = 3.1.(-2) + 2.(-1).(-3) + 2.1.0$  
$det(M23) = -6 + 6 = 0$  


dibuktikan dengan menggunakan numpy python 

In [6]:
import numpy as np
M23 = np.array([[3,2,5], [3,2,2], [3,2,4]])
detM23 = np.linalg.det(M23)
print(round(detM23))

0


**8. **keempat : $M_{24}$****


$\begin{matrix}
  det(M24) = \begin{bmatrix}
    2 & 3 & 4 \\
    3 & 2 & 2 \\
    3 & 2 & 5
  \end{bmatrix}
\end{matrix}
$  


selanjutnya tulis rumus determinan, dan mengambil baris ke-2  
$det(M21) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$   


selanjutnya tentukan kofaktor dari matriks yang $M_{21}, M_{22}, M_{23}$  
* $c_{21} = (-1)^{2 + 1} det(KM21)$   

$
\begin{matrix}
  det(KM21) = \begin{bmatrix}
    3 & 4 \\
    2 & 5
  \end{bmatrix}
\end{matrix}
$  
$det(KM21) = 3.5- 2.4 = 15 - 8 = 7$  


hasil 
$c_{21} = -1*7$  


* $c_{22} = (-1)^{2+2}det(KM22)$   

$
\begin{matrix}
  det(KM22) = \begin{bmatrix}
    2 & 4 \\
    3 & 5
  \end{bmatrix}
\end{matrix}
$  
$det(KM22) = 2.5 - 3.4 = 10 - 12 = -2$  


hasil
$c_{22} = -1*-2$  


* $c_{23} = (-1)^{2+3}det(KM23)$  
 
$
\begin{matrix}
  det(KM23) = \begin{bmatrix}
    2 & 3 \\
    3 & 2
  \end{bmatrix}
\end{matrix}
$  
$det(KM23) = 2.2 - 3.3 = 4 - 9 = -5$  


hasil
$c_{23} = -1*-5$  


**hasil akhir dari $M_{24}$**  
$det(M24) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$  
$det(M24) = 3.(-1).7 + 2.1.(-2) + 2.(-1).(-5)$  
$det(M24) = -21 - 4 + 10 = -15$  


dibuktikan dengan menggunakan numpy python 

In [7]:
import numpy as np
M23 = np.array([[2,3,4], [3,2,2], [3,2,5]])
detM23 = np.linalg.det(M23)
print(round(detM23))

-15


**9. **langkah terakhir mencari determinan A****  


$det(M_{21}) = 8$  
$det(M_{22}) = 17$  
$det(M_{23}) = 0$  
$det(M_{24}) = -15$  

selanjutnya subtitusi nilai determinan dari matriks minornya  

$c_{21} = (-1)^{2+1}det(M_{21}) = -1.8$  
$c_{22} = (-1)^{2+1}det(M_{22}) = 1.17$  
$c_{23} = (-1)^{2+1}det(M_{23}) = -1.0$  
$c_{24} = (-1)^{2+1}det(M_{24}) = -1.-15$  

$a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} + a_{24}c_{24} =$
$1.(-1).8 + 1.1.17 + 1.(-1).0 + 1.(-1).(-15) =$
$-8 + 17 + 0 + 15 = 4$  


In [3]:
import numpy as np
A = np.array([[2,3,4,5], [1,1,1,1], [3,2,2,2], [3,2,5,4]])
detA = np.linalg.det(A)
print("A: \n", A)
print()
print("Determinan A = ", round(detA))

A: 
 [[2 3 4 5]
 [1 1 1 1]
 [3 2 2 2]
 [3 2 5 4]]

Determinan A =  4
