# Aljabar Matriks

## Matriks.[1]

Mengenai tentang **Pengertian Matriks** dapat disimpulkan sebagai berikut :  
* Matriks adalah kumpulan bilangan yang disusun berdasarkan baris dan kolom serta ditempatkan didalam tanda kurung biasa ( ) atau tanda kurung siku [ ]. Untuk memberi nama pada matriks menggunakan huruf kapital seperti A, B, C dan seterusnya.  

$$
\begin{matrix}
A = \begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6 
  \end{bmatrix}
\end{matrix}
$$

* Matriks mempunyai ukuran yangg disebut ordo. Ordo pada matriks ini berdasarkan dari banyak baris dan dikali banyak kolom. Jadi kalo matriks memiliki baris(m) dan kolom(n), maka ordo dari matriks tersebut m x n  
* Bilangan yang ada di dalam matriks disebut elemen maktriks. Jika matrik dinotasikan dengan huruf kapital maka elemen matriks dinotasikan degan huruf kecil.  
seperti halnya contoh berikut :  

$$
\begin{matrix}
A = \begin{bmatrix}
    a & b & c \\
    d & e & f \\
    g & h & i 
  \end{bmatrix}
\end{matrix}
$$

## Operasi pada matriks. [2]

Ada beberapa **opersi pada matriks** diantaranya sebagai berikut :  
* Penjumlahan matriks syarat untuk penjumlahan matriks harus memiliki ordo yang sama misal matriks A memiliki baris kolom 2x2 matriks B memiliki baris kolom 2x2, maka hasil penjumlahanya dari menjumlahkan setiap elemen matriks A dan matriks B.
Contoh sebgai berikut :  

$$
\begin{matrix}
A = \begin{bmatrix}
    1 & 2 \\
    3 & 4  
  \end{bmatrix}
\end{matrix}  


\begin{matrix}
B = \begin{bmatrix}
    4 & 3 \\
    2 & 1 
  \end{bmatrix}
\end{matrix}
$$

$$
\begin{matrix}
A+B = \begin{bmatrix}
    1+4 & 2+3 \\
    3+2 & 4+1 
  \end{bmatrix}
\end{matrix}  
$$  
$$
\begin{matrix}
A+B = \begin{bmatrix}
    5 & 5 \\
    5 & 5 
  \end{bmatrix}
\end{matrix}
$$

* Pengurangan matriks sebenaranya pengurangan matriks sama dengan penhjumlahan matriks yaitu harus memiliki ordo yang sama.  
Contoh sebagai berikut :  

$$
\begin{matrix}
A = \begin{bmatrix}
    -2 & 3 \\
    1 & 2 
  \end{bmatrix}
\end{matrix}  


\begin{matrix}
B = \begin{bmatrix}
    4 & 1 \\
    2 & 3 
  \end{bmatrix}
\end{matrix}
$$  

$$
\begin{matrix}
A-B = \begin{bmatrix}
    (-2)-2 & 3-1 \\
    1-2 & 2-3 
  \end{bmatrix}
\end{matrix}  
$$  
$$
\begin{matrix}
A+B = \begin{bmatrix}
    -6 & 2 \\
    1 & -1 
  \end{bmatrix}
\end{matrix}
$$

* Perkalian Matriks Syarat untuk perkalian matriks adalah pada matriks pertama harus memiliki jumlah kolom yang sama dengan jumlah baris pada matriks kedua.  
contoh :  

$$
\begin{matrix}
A = \begin{bmatrix}
    6 & 3 \\
    4 & 8 
  \end{bmatrix}
\end{matrix}  


\begin{matrix}
B = \begin{bmatrix}
    1 \\
    2 
  \end{bmatrix}
\end{matrix}
$$  

$$
\begin{matrix}
A*B = \begin{bmatrix}
    6*1 & 3*2 \\
    4*1 & 8*2 
  \end{bmatrix}
\end{matrix}  
$$  
$$
\begin{matrix}
A*B = \begin{bmatrix}
    6 + 6 \\
    4 + 16 
  \end{bmatrix}
\end{matrix}  
$$  
$$
\begin{matrix}
A*B = \begin{bmatrix}
    12 \\
    20 
  \end{bmatrix}
\end{matrix}  
$$  

## Implementasi matriks dengan numpy. [3]

**Implementasi matriks dengan numpy** Pada bahasa pemrograman yang berbasis matrik seperti Matlab dan python numpy, hampir semua penyebab eror itu karena ketidaksesuian ukuran dari matriks. tentunya untuk bisa mengoperasikan dua buah matriks atau lebih itu harus memiliki ukuran yang sama atau sesuai. Hal dasar pada pengubahan bentuk matriks pada numpy adalah operasi tersebut hanya memengaruhi pada struktur larik (array), bukan datanya. Operasi tersebut dilakukan tanpa menyalin memori sehinggan bisa menghemat memori. Ada empat teknik dasar untuk mengubah matriks, tiga teknik mempropses array tanpa menyalin memori yaitu transpose, reshape, flatten. Dan satu teknik memperoses array dengan menyalin memorinya yaitu ravel. Untuk lebih jelasnya saya paparkan sebagai berikut :  
1. Tranpose  
Transpose matriks merupakan proses mengubah baris ke-1 menjasdi kolom ke-1,baris ke-2 menjadi kolom ke-2, baris ke-n menjadi kolom ke-n
Perintah dasar untuk bentuk matriks menggunakan Tranpose :
    * .T  
    adalah atribut  
    * .transpose()  
    adalah metode  
    * np.transpose()  
    adalah fungsi   


operasi .T dan .transpose tidak menerima argumen() hanya pada operasi np.transpose yang bisa menerima argumen  
Buat secara manual,otomatis  

In [1]:
import numpy as np
A = np.array([[3,2,5],[4,1,3]])
B = np.array([[5,3,0],[6,-4,1]])
C = np.array([[-3,5],[5,-3]])

print(f'A = \n{A}')
print(f'A.T = \n{A.T}')
print(f'B = \n{B}')
print(f'B.transpose = \n{B.transpose()}')
print(f'C = \n{C}')
print(f'np.transpose(C) = \n{np.transpose(C)}')

A = 
[[3 2 5]
 [4 1 3]]
A.T = 
[[3 4]
 [2 1]
 [5 3]]
B = 
[[ 5  3  0]
 [ 6 -4  1]]
B.transpose = 
[[ 5  6]
 [ 3 -4]
 [ 0  1]]
C = 
[[-3  5]
 [ 5 -3]]
np.transpose(C) = 
[[-3  5]
 [ 5 -3]]


In [2]:
A = np.random.randint(10,size=(3,3))
print('A =',A)
print('A.T =',A.T)

A = [[9 3 3]
 [0 0 3]
 [6 2 5]]
A.T = [[9 0 6]
 [3 0 2]
 [3 3 5]]


2. Reshape  
Operasi dasar Reshape digunakan untuk mengubah bentuk matriks, misal dari ukuran (m, n) menjadi (n, m).Perintah reshape tidak sama dengan transpose. Ketika perintah reshape matrix A (m, n) menjadi B (n, m) itu berlaku hanya ukurannya yang dibalik, bukan matriksnya Perintah dasar untuk bentuk matriks menggunakan Reshape :  

    * .shape  
    adalah atribut 
    * .reshape (baris, kolom)  
    adalah atribut  
    *  np.reshape(namaMatriks, (baris, kolom)  
    adalah metode  

operasi .T dan .transpose tidak menerima argumen() hanya pada operasi np.transpose yang bisa menerima argumen

In [3]:
import numpy as np
A = np.array([[3,2,5],[4,1,3]])
B = np.array([[5,3,0],[6,-4,1]])

print('A =',A)
print('A.shape =',A.shape)

A = [[3 2 5]
 [4 1 3]]
A.shape = (2, 3)


3. Flatten  
adalah salah satu bentuk mengubah matriks dengan aturan hanya menyalin matriks asli tanpa mengubah matriks asli itu sendiri Perintah dasar untuk bentuk matriks menggunakan Flatten :  
    * .flatten()

In [4]:
import numpy as np
A = np.array([[3,2,5],[4,1,3]])

print('A =',A)
print('A.flatten =',A.flatten())

A = [[3 2 5]
 [4 1 3]]
A.flatten = [3 2 5 4 1 3]


4. Ravel  
sama dengan flatten, ravel adalah salah satu bentuk mengubah matriks dengan menyalin matriks asli dan dapat mengubah matriks asli itu sendiri Perintah dasar untuk bentuk matriks menggunakan Flatten :  
    * .ravel() 

In [5]:
import numpy as np
A = np.array([[3,2,5],[4,1,3]])

print('A =',A)
print('A.ravel =',A.ravel())

A = [[3 2 5]
 [4 1 3]]
A.ravel = [3 2 5 4 1 3]


## Link Referensi  
[1] https://www.ruangguru.com/blog/mengenal-matriks-dalam-matematika-pengertian-jenis-dan-transpose  
[2] https://www.ruangguru.com/blog/matematika-kelas-11-operasi-aljabar-pada-matriks-penjumlahan-pengurangan-dan-perkalian  
[3] https://dqlab.id/membuat-bentuk-matriks-dengan-numpy-array-python