# Implementasi Power Methode Pada PageRank

In [5]:
import numpy as np 
A = np.array([[0,0,0,0,1/3],[0,0,1/2,1,1/3],[1/3,0,0,0,1/3],[1/3,0,1/2,0,0],[1/3,1,0,0,0]])
print(A)

[[0.         0.         0.         0.         0.33333333]
 [0.         0.         0.5        1.         0.33333333]
 [0.33333333 0.         0.         0.         0.33333333]
 [0.33333333 0.         0.5        0.         0.        ]
 [0.33333333 1.         0.         0.         0.        ]]


In [6]:
def kaliMatriks(A,v0):
  vBaru = A@v0
  return vBaru

def hasilHitung(vBaru,vlama):
  temp = 0
  for i in range(len(vBaru)):
    temp += (vBaru[i] - vlama[i])**2
  return temp

def converenge(A,v0,toleransi):
  temp = 1
  vBaru = kaliMatriks(A,v0)
  iterasi = hasilHitung(vBaru,v0)
  print(f'v{temp} = {vBaru}')
  print(f'iterasi ke-{temp} = {iterasi}')
  print()
  while iterasi > toleransi :
    vBaru2 = kaliMatriks(A,vBaru)
    iterasi = hasilHitung(vBaru2,vBaru)
    print(f'v{temp+1} = {vBaru}')
    print(f'iterasi ke-{temp+1} = {iterasi}')
    print()
    vBaru = vBaru2
    temp += 1
  return f'urutan = {pageRank(vBaru2)}'

def pageRank(vBaru):
  return np.sort(vBaru,axis=0)[::-1]

A = np.array([[0,0,0,0,1/3],[0,0,1/2,1,1/3],[1/3,0,0,0,1/3],[1/3,0,1/2,0,0],[1/3,1,0,0,0]])
v0 = np.array([[0.2],[0.2],[0.2],[0.2],[0.2]])
toleransi = 0.01
result = converenge(A,v0,toleransi)
print(result)

v1 = [[0.06666667]
 [0.36666667]
 [0.13333333]
 [0.16666667]
 [0.26666667]]
iterasi ke-1 = [0.05555556]

v2 = [[0.06666667]
 [0.36666667]
 [0.13333333]
 [0.16666667]
 [0.26666667]]
iterasi ke-2 = [0.02395062]

v3 = [[0.08888889]
 [0.32222222]
 [0.11111111]
 [0.08888889]
 [0.38888889]]
iterasi ke-3 = [0.00768176]

urutan = [[0.35185185]
 [0.27407407]
 [0.15925926]
 [0.12962963]
 [0.08518519]]
