# Perkalian Matriks

In [1]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[2,2],[2,2]])

print(f'matriks A \n{A}')
print(f'matriks B \n{B}')

# perkalian biasa
C = A*B
print('hasil perkalian biasa')
print(C)

# perkalian mariks
D1 = np.dot(A,B)
print('hasil D1')
print(D1)
D2 = A.dot(B)
print('hasil D2')
print(D2)

matriks A 
[[1 2]
 [3 4]]
matriks B 
[[2 2]
 [2 2]]
hasil perkalian biasa
[[2 4]
 [6 8]]
hasil D1
[[ 6  6]
 [14 14]]
hasil D2
[[ 6  6]
 [14 14]]
