# Aljabar Matriks

## Matriks. [1]

  * Matriks adalah kumpulan bilangan yang disusun berdasarkan baris dan kolom serta ditempatkan didalam tanda kurung biasa ( ) atau tanda kurung siku [ ]. Untuk memberi nama pada matriks menggunakan huruf kapital seperti A, B, C dan seterusnya.

$$ A = 
\begin {bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

  * Matriks mempunyai ukuran yangg disebut ordo. Ordo pada matriks ini berdasarkan dari banyak baris dan dikali banyak kolom. Jadi kalo matriks memiliki baris(m) dan kolom(n), maka ordo dari matriks tersebut m x n
  * Bilangan yang ada di dalam matriks disebut elemen maktriks. Jika matrik dinotasikan dengan huruf kapital maka elemen matriks dinotasikan degan huruf kecil.  
  seperti halnya contoh berikut :

$$ A = 
\begin {bmatrix}
a & b & c\\
d & e & f\\
f & g & h 
\end{bmatrix}
$$

## Operasi pada matriks. [2]

  1. Penjumlahan matriks
    syarat untuk penjumlahan matriks harus memiliki ordo yang sama misal matriks A memiliki baris kolom 2x2 matriks B memiliki baris kolom 2x2, maka hasil penjumlahanya dari menjumlahkan setiap elemen matriks A dan matriks B.  
    Contoh sebgai berikut :

$$ A = 
\begin {bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

$$ B = 
\begin {bmatrix}
4 & 3 \\
2 & 1
\end{bmatrix}
$$

maka jika A+B :
$$ A+B = 
\begin {bmatrix}
1+4 & 2+3 \\
3+2 & 4+1
\end{bmatrix}
$$

$$ A+B = 
\begin {bmatrix}
5 & 5 \\
5 & 5
\end{bmatrix}
$$

  2. Pengurangan matriks
    sebenaranya pengurangan matriks sama dengan penhjumlahan matriks yaitu harus memiliki ordo yang sama.   
    Contoh sebagai berikut :


$$ A = 
\begin {bmatrix}
-2 & 3 \\
1 & 2
\end{bmatrix}
$$

$$ B = 
\begin {bmatrix}
4 & 1 \\
2 & 3
\end{bmatrix}
$$

maka jika A-B :
$$ A-B = 
\begin {bmatrix}
(-2)-2 & 3-1 \\
1-2 & 2-3
\end{bmatrix}
$$

$$ A-B = 
\begin {bmatrix}
-6 & 2 \\
1 & 1
\end{bmatrix}
$$

  3. Perkalian Matriks
    Syarat untuk perkalian matriks adalah pada matriks pertama harus memiliki jumlah kolom yang sama dengan jumlah baris pada matriks kedua.  
    contoh 
$$ A = 
\begin {bmatrix}
6 & 3 \\
4 & 8
\end{bmatrix}
$$  
$$ B = 
\begin {bmatrix}
1  \\
2 
\end{bmatrix}
$$
    
maka jika matriks AxB :  
$$ AxB = 
\begin {bmatrix}
6x1 & 3x2 \\
4x1 & 8x2
\end{bmatrix}
$$ 

$$ AxB =
\begin {bmatrix}
6+6  \\
4+16
\end{bmatrix}
$$ 

$$ AxB =
\begin {bmatrix}
12  \\
20 
\end{bmatrix}
$$ 


## Implementasi matriks dengan numpy. [3]

Pada bahasa pemrograman yang berbasis matrik seperti Matlab dan python numpy, hampir semua penyebab eror itu karena ketidaksesuian ukuran dari matriks. tentunya untuk bisa mengoperasikan dua buah matriks atau lebih itu harus memiliki ukuran yang sama atau sesuai. Hal dasar pada pengubahan bentuk matriks pada numpy adalah operasi tersebut hanya memengaruhi pada struktur larik (array), bukan datanya. Operasi tersebut dilakukan tanpa menyalin memori sehinggan bisa menghemat memori. Ada empat teknik dasar untuk mengubah matriks, tiga teknik mempropses array tanpa menyalin memori yaitu transpose, reshape, flatten. Dan satu teknik memperoses array dengan menyalin memorinya yaitu ravel.

  1.  Tranpose
    Transpose matriks merupakan proses mengubah baris ke-1 menjasdi kolom ke-1,baris ke-2 menjadi kolom ke-2, baris ke-n menjadi kolom ke-n  
    Perintah dasar untuk bentuk matriks menggunakan Tranpose :  
      a. .T  
        adalah atribut  
      b. .transpose()  
        adalah metode  
      c. np.transpose()  
        adalah fungsi  
      operasi .T dan .transpose tidak menerima argumen() hanya pada operasi np.transpose yang bisa menerima argumen 

Buat secara manual

In [1]:
import numpy as np
A = np.array([[3,2,5],[4,1,3]])
B = np.array([[5,3,0],[6,-4,1]])
C = np.array([[-3,5],[5,-3]])

print('A =',A)
print('A.T =',A.T)
print('B =',B)
print('B.transpose =',B.transpose())
print('C =',C)
print('np.transpose(C) =',np.transpose(C))



A = [[3 2 5]
 [4 1 3]]
A.T = [[3 4]
 [2 1]
 [5 3]]
B = [[ 5  3  0]
 [ 6 -4  1]]
B.transpose = [[ 5  6]
 [ 3 -4]
 [ 0  1]]
C = [[-3  5]
 [ 5 -3]]
np.transpose(C) = [[-3  5]
 [ 5 -3]]


Buat secara otomatis

In [2]:
A = np.random.randint(10,size=(3,3))
print('A =',A)
print('A.T =',A.T)

A = [[4 4 6]
 [6 5 4]
 [6 6 5]]
A.T = [[4 6 6]
 [4 5 6]
 [6 4 5]]


  2.  Reshape
    Operasi dasar Reshape digunakan untuk mengubah bentuk matriks, misal dari ukuran (m, n) menjadi (n, m).Perintah reshape tidak sama dengan transpose. Ketika perintah reshape matrix A (m, n) menjadi B (n, m) itu berlaku hanya ukurannya yang dibalik, bukan matriksnya
    Perintah dasar untuk bentuk matriks menggunakan Reshape :
      a. .shape
        adalah atribut
      b. .reshape(baris, kolom)
        adalah atribut  
      c. np.reshape(namaMatriks, (baris, kolom) 
        adalah metode   
      operasi .T dan .transpose tidak menerima argumen() hanya pada operasi np.transpose yang bisa menerima argumen 

In [5]:
import numpy as np
A = np.array([[3,2,5],[4,1,3]])
B = np.array([[5,3,0],[6,-4,1]])

print('A =',A)
print('A.shape =',A.shape)




A = [[3 2 5]
 [4 1 3]]
A.shape = (2, 3)


  3.  Flatten
    adalah salah satu bentuk mengubah matriks dengan aturan hanya menyalin matriks asli tanpa mengubah matriks asli itu sendiri 
    Perintah dasar untuk bentuk matriks menggunakan Flatten :
      a. .flatten()

In [6]:
import numpy as np
A = np.array([[3,2,5],[4,1,3]])

print('A =',A)
print('A.flatten =',A.flatten())

A = [[3 2 5]
 [4 1 3]]
A.flatten = [3 2 5 4 1 3]


  4.  Ravel
    sama dengan flatten, ravel adalah salah satu bentuk mengubah matriks dengan menyalin matriks asli dan dapat mengubah matriks asli itu sendiri 
    Perintah dasar untuk bentuk matriks menggunakan Flatten :
      a. .ravel()

In [7]:
import numpy as np
A = np.array([[3,2,5],[4,1,3]])

print('A =',A)
print('A.ravel =',A.ravel())

A = [[3 2 5]
 [4 1 3]]
A.ravel = [3 2 5 4 1 3]


## Link 
[1] https://www.ruangguru.com/blog/mengenal-matriks-dalam-matematika-pengertian-jenis-dan-transpose  
[2] https://www.ruangguru.com/blog/matematika-kelas-11-operasi-aljabar-pada-matriks-penjumlahan-pengurangan-dan-perkalian  
[3] https://dqlab.id/membuat-bentuk-matriks-dengan-numpy-array-python